### PR TITLE
Linters!

### PR DESCRIPTION
**Pull request by hidalgopl**
I think adding [golangci-lint](https://github.com/golangci/golangci-lint) as non-blocking step in pipeline would be good for maintaining code quality. In near future we can also tackle issues found by linter and make this check mandatory.

### CODE REVIEW

**Review by ldx — COMMENTED** [review]
Cool! Since there's only a handful of lint errors, we should fix those to start with a green build.

**Comment by ldx** [comment]
BTW I just stumbled upon this repo: https://github.com/github/super-linter, might be a more comprehensive all-in-one solution.

**Comment by hidalgopl** [comment]
> BTW I just stumbled upon this repo: https://github.com/github/super-linter, might be a more comprehensive all-in-one solution.

thanks! This looks cool, added it. Actually it scans sh files in repo as well. Do we want to have other language linters enabled here, or just golang one?

**Comment by ldx** [comment]
> > BTW I just stumbled upon this repo: https://github.com/github/super-linter, might be a more comprehensive all-in-one solution.
> 
> thanks! This looks cool, added it. Actually it scans sh files in repo as well. Do we want to have other language linters enabled here, or just golang one?

I'd suggest:
1. We enable only the go linter.
2. Fix the warnings.
3. Merge this PR.
4. Create issues for enabling the bash, TF, etc linters one by one later on, and fix those warnings at that time.

**Pull request closed without merging**
